### ISSUE TITLE
What did happen to the travis file?

### ISSUE THREAD

**Issue by sinamr88** [epfl-lasa/kuka-rviz-simulation#10]
The package did not even exist on travis any more ...! Hence, I activated it again.. But something is still wrong......Who did change it?

**Comment by nbfigueroa** [comment]
Idk, I just removed a directory and suddenly it's not working. Now I added a new travis file but I get some errors, which I don't have the time to debug right now :)

**Comment by gpldecha** [comment]
But you should debug :(

**Comment by felixduvallet** [comment]
I'm (very slowly) looking into the original travis failure (catkin_pk) that (I think) you fixed already.

FYI, the best way to specify dependencies is not directly inside the .travis.yml file, but in your package manifest: see the [instructions] and search rosdep for your dependency. This way, your package dependencies are "self contained" and all you need is to run "rosdep install" to grab all the dependencies.

  [instructions]: https://github.com/felixduvallet/ros-travis-integration#handling-dependencies

**Comment by nbfigueroa** [comment]
Hi Felix! We discovered that for some reason travis wasn't working due to this catking_pkg, which is supposed to be pre-installed with all the ros dependencies.  We figured out we have to manually install it manually now; i.e. add it to the yml file as we did. Then I also was getting another error from a missing python module, so I added it too. These seem to be errors related to python itself, perhaps they upgraded their version? (we got the same catkin_pkg errors with other packages)

**Comment by felixduvallet** [comment]
Hey guys,

I found the issue, it had to do with an Ubuntu image upgrade (on the Travis side) that moved the installed location of python. For full details, see https://github.com/felixduvallet/ros-travis-integration/issues/9

I suggest you upgrade your travis file (for this repository and others). This will ensure all dependencies that are installed via rosdep are correctly found.

**Comment by nbfigueroa** [comment]
Thanks! @felixduvallet we'll do that :)
